export const yearLevels = [
  "First year",
  "Second year",
  "Third year",
  "Fourth year",
  "Fifth year or above",
] as const;

export const undergraduateDegrees = [
  "Bachelor of Architectural Studies",
  "Bachelor of Arts",
  "Bachelor of Biomedical Science",
  "Bachelor of Commerce",
  "Bachelor of Communication",
  "Bachelor of Dance Studies",
  "Bachelor of Design",
  "Bachelor of Early Childhood Studies",
  "Bachelor of Education (Teaching)",
  "Bachelor of Education (Teaching English to Speakers of Other Languages)",
  "Bachelor of Engineering (Honours)",
  "Bachelor of Fine Arts",
  "Bachelor of Global Studies",
  "Bachelor of Health Sciences",
  "Bachelor of Laws",
  "Bachelor of Laws (Honours)",
  "Bachelor of Medical Imaging (Honours)",
  "Bachelor of Medicine and Bachelor of Surgery",
  "Bachelor of Music",
  "Bachelor of Nursing",
  "Bachelor of Nursing (Honours)",
  "Bachelor of Optometry",
  "Bachelor of Pharmacy",
  "Bachelor of Pharmacy (Honours)",
  "Bachelor of Property",
  "Bachelor of Psychology",
  "Bachelor of Science",
  "Bachelor of Social Justice Studies",
  "Bachelor of Social Work",
  "Bachelor of Social Work (Honours)",
  "Bachelor of Sport, Health and Physical Education",
  "Bachelor of Urban Planning (Honours)",
] as const;

export const teachOutUndergraduateDegrees = [
  "Bachelor of Advanced Science (Honours)",
  "Bachelor of Engineering",
  "Bachelor of Human Services",
  "Bachelor of Medical Imaging",
  "Bachelor of Theology",
] as const;

export const undergraduateConjointDegrees = [
  "Bachelor of Arts/Bachelor of Biomedical Science",
  "Bachelor of Arts/Bachelor of Commerce",
  "Bachelor of Arts/Bachelor of Communication",
  "Bachelor of Arts/Bachelor of Design",
  "Bachelor of Arts/Bachelor of Engineering (Honours)",
  "Bachelor of Arts/Bachelor of Fine Arts",
  "Bachelor of Arts/Bachelor of Global Studies",
  "Bachelor of Arts/Bachelor of Health Sciences",
  "Bachelor of Arts/Bachelor of Laws",
  "Bachelor of Arts/Bachelor of Laws (Honours)",
  "Bachelor of Arts/Bachelor of Music",
  "Bachelor of Arts/Bachelor of Science",
  "Bachelor of Biomedical Science/Bachelor of Commerce",
  "Bachelor of Biomedical Science/Bachelor of Communication",
  "Bachelor of Biomedical Science/Bachelor of Engineering (Honours)",
  "Bachelor of Biomedical Science/Bachelor of Fine Arts",
  "Bachelor of Biomedical Science/Bachelor of Global Studies",
  "Bachelor of Biomedical Science/Bachelor of Health Sciences",
  "Bachelor of Biomedical Science/Bachelor of Laws",
  "Bachelor of Biomedical Science/Bachelor of Laws (Honours)",
  "Bachelor of Biomedical Science/Bachelor of Science",
  "Bachelor of Biomedical Science/Bachelor of Sport, Health and Physical Education",
  "Bachelor of Commerce/Bachelor of Design",
  "Bachelor of Commerce/Bachelor of Engineering (Honours)",
  "Bachelor of Commerce/Bachelor of Global Studies",
  "Bachelor of Commerce/Bachelor of Health Sciences",
  "Bachelor of Commerce/Bachelor of Laws",
  "Bachelor of Commerce/Bachelor of Laws (Honours)",
  "Bachelor of Commerce/Bachelor of Music",
  "Bachelor of Commerce/Bachelor of Property",
  "Bachelor of Commerce/Bachelor of Science",
  "Bachelor of Commerce/Bachelor of Sport, Health and Physical Education",
  "Bachelor of Communication/Bachelor of Global Studies",
  "Bachelor of Communication/Bachelor of Laws",
  "Bachelor of Communication/Bachelor of Laws (Honours)",
  "Bachelor of Design/Bachelor of Engineering (Honours)",
  "Bachelor of Design/Bachelor of Fine Arts",
  "Bachelor of Design/Bachelor of Global Studies",
  "Bachelor of Design/Bachelor of Science",
  "Bachelor of Engineering (Honours)/Bachelor of Global Studies",
  "Bachelor of Engineering (Honours)/Bachelor of Music",
  "Bachelor of Engineering (Honours)/Bachelor of Science",
  "Bachelor of Fine Arts/Bachelor of Science",
  "Bachelor of Global Studies/Bachelor of Health Sciences",
  "Bachelor of Global Studies/Bachelor of Laws",
  "Bachelor of Global Studies/Bachelor of Laws (Honours)",
  "Bachelor of Global Studies/Bachelor of Science",
  "Bachelor of Health Sciences/Bachelor of Laws",
  "Bachelor of Health Sciences/Bachelor of Laws (Honours)",
  "Bachelor of Health Sciences/Bachelor of Science",
  "Bachelor of Music/Bachelor of Laws",
  "Bachelor of Music/Bachelor of Laws (Honours)",
  "Bachelor of Music/Bachelor of Science",
  "Bachelor of Science/Bachelor of Laws",
  "Bachelor of Science/Bachelor of Laws (Honours)",
] as const;

export const teachOutConjointDegrees = [
  "Bachelor of Advanced Science (Honours)/Bachelor of Commerce",
  "Bachelor of Advanced Science (Honours)/Bachelor of Communication",
  "Bachelor of Advanced Science (Honours)/Bachelor of Design",
  "Bachelor of Advanced Science (Honours)/Bachelor of Engineering (Honours)",
  "Bachelor of Advanced Science (Honours)/Bachelor of Fine Arts",
  "Bachelor of Advanced Science (Honours)/Bachelor of Global Studies",
  "Bachelor of Advanced Science (Honours)/Bachelor of Health Sciences",
  "Bachelor of Advanced Science (Honours)/Bachelor of Laws",
  "Bachelor of Advanced Science (Honours)/Bachelor of Laws (Honours)",
  "Bachelor of Advanced Science (Honours)/Bachelor of Music",
  "Bachelor of Advanced Science (Honours)/Bachelor of Nursing",
  "Bachelor of Advanced Science (Honours)/Bachelor of Property",
  "Bachelor of Arts/Bachelor of Advanced Science (Honours)",
  "Bachelor of Arts/Bachelor of Fine Arts (Honours)",
  "Bachelor of Commerce/Bachelor of Fine Arts",
  "Bachelor of Communication/Bachelor of Commerce",
  "Bachelor of Communication/Bachelor of Engineering (Honours)",
  "Bachelor of Communication/Bachelor of Fine Arts",
  "Bachelor of Communication/Bachelor of Health Sciences",
  "Bachelor of Communication/Bachelor of Science",
  "Bachelor of Design/Bachelor of Health Sciences",
  "Bachelor of Design/Bachelor of Laws",
  "Bachelor of Design/Bachelor of Laws (Honours)",
  "Bachelor of Design/Bachelor of Music",
  "Bachelor of Design/Bachelor of Property",
  "Bachelor of Engineering (Honours)/Bachelor of Fine Arts",
  "Bachelor of Engineering (Honours)/Bachelor of Laws",
  "Bachelor of Engineering (Honours)/Bachelor of Laws (Honours)",
  "Bachelor of Engineering (Honours)/Bachelor of Property",
  "Bachelor of Fine Arts/Bachelor of Global Studies",
  "Bachelor of Fine Arts/Bachelor of Health Sciences",
  "Bachelor of Fine Arts/Bachelor of Laws",
  "Bachelor of Fine Arts/Bachelor of Laws (Honours)",
  "Bachelor of Fine Arts/Bachelor of Music",
  "Bachelor of Fine Arts (Honours)/Bachelor of Science",
  "Bachelor of Global Studies/Bachelor of Music",
  "Bachelor of Global Studies/Bachelor of Property",
  "Bachelor of Health Sciences/Bachelor of Nursing",
  "Bachelor of Nursing/Bachelor of Science",
  "Bachelor of Property/Bachelor of Laws",
  "Bachelor of Property/Bachelor of Laws (Honours)",
  "Bachelor of Property/Bachelor of Science",
] as const;

export const programmeGroups = [
  { label: "Undergraduate degrees", options: undergraduateDegrees },
  {
    label: "Current and teach-out undergraduate degrees",
    options: teachOutUndergraduateDegrees,
  },
  {
    label: "Undergraduate conjoint degrees",
    options: undergraduateConjointDegrees,
  },
  {
    label: "Current and teach-out conjoint degrees",
    options: teachOutConjointDegrees,
  },
] as const;

export const programmes = [
  ...undergraduateDegrees,
  ...teachOutUndergraduateDegrees,
  ...undergraduateConjointDegrees,
  ...teachOutConjointDegrees,
] as const;

export const departments = [
  "Arts and Education",
  "Business School",
  "Engineering and Design",
  "Auckland Law School",
  "Medical and Health Sciences",
  "Science",
  "Auckland Bioengineering Institute",
  "Liggins Institute",
  "Te Wānanga o Waipapa",
] as const;

export const majors = [
  "Accounting",
  "Anthropology",
  "Biological Sciences",
  "Biomedical Science",
  "Business Analytics",
  "Chemistry",
  "Civil Engineering",
  "Communication",
  "Computer Science",
  "Criminology",
  "Data Science",
  "Economics",
  "Education",
  "Electrical and Electronic Engineering",
  "Engineering Science",
  "English",
  "Finance",
  "Geography",
  "Global Studies",
  "History",
  "Information Systems",
  "Law",
  "Linguistics",
  "Management",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Music",
  "Nursing",
  "Pharmacology",
  "Philosophy",
  "Politics and International Relations",
  "Psychology",
  "Software Engineering",
  "Statistics",
] as const;
