export const yearLevels = [
  "First year",
  "Second year",
  "Third year",
  "Fourth year",
  "Fifth year or above",
  "Postgraduate",
  "Doctoral",
] as const;

export const programmes = [
  "Bachelor of Architectural Studies",
  "Bachelor of Arts",
  "Bachelor of Commerce",
  "Bachelor of Communication",
  "Bachelor of Engineering (Honours)",
  "Bachelor of Fine Arts",
  "Bachelor of Global Studies",
  "Bachelor of Health Sciences",
  "Bachelor of Laws",
  "Bachelor of Medicine and Bachelor of Surgery",
  "Bachelor of Music",
  "Bachelor of Nursing",
  "Bachelor of Science",
  "Bachelor of Social Work",
  "Bachelor of Urban Planning (Honours)",
  "Conjoint programme",
  "Postgraduate programme",
] as const;

export const departments = [
  "Arts and Education",
  "Business School",
  "Engineering and Design",
  "Auckland Law School",
  "Medical and Health Sciences",
  "Science",
  "Auckland Bioengineering Institute",
  "Liggins Institute",
  "Te Wānanga o Waipapa",
] as const;

export const majors = [
  "Accounting",
  "Anthropology",
  "Biological Sciences",
  "Biomedical Science",
  "Business Analytics",
  "Chemistry",
  "Civil Engineering",
  "Communication",
  "Computer Science",
  "Criminology",
  "Data Science",
  "Economics",
  "Education",
  "Electrical and Electronic Engineering",
  "Engineering Science",
  "English",
  "Finance",
  "Geography",
  "Global Studies",
  "History",
  "Information Systems",
  "Law",
  "Linguistics",
  "Management",
  "Marketing",
  "Mathematics",
  "Mechanical Engineering",
  "Medicine",
  "Music",
  "Nursing",
  "Pharmacology",
  "Philosophy",
  "Politics and International Relations",
  "Psychology",
  "Software Engineering",
  "Statistics",
] as const;
